ose exec web 
pytest
============================= test session starts ==============================
platform linux -- Python 3.9.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
django: settings: web.settings (from env)
rootdir: /opt/web, configfile: pytest.ini
plugins: django-4.5.2
collecting 0 items                                                  collected 3 items                                                              

blog/tests/test_post.py ..F                                              [100%]

=================================== FAILURES ===================================
_______________________ test_default_posted_time_is_set ________________________

    @pytest.mark.django_db
    def test_default_posted_time_is_set():
        post = Post(title="Test", text="Testing")
        post.save()
    
        assert post.id
        assert post.posted_at is not None
>       assert post.posted_at.date() == datetime.datetime.now().date()
E       AssertionError: assert datetime.date(2022, 2, 9) == datetime.date(2022, 2, 10)
E        +  where datetime.date(2022, 2, 9) = <built-in method date of datetime.datetime object at 0x401ac323f0>()
E        +    where <built-in method date of datetime.datetime object at 0x401ac323f0> = datetime.datetime(2022, 2, 9, 15, 58, 50, 111771).date
E        +      where datetime.datetime(2022, 2, 9, 15, 58, 50, 111771) = <Post: Test>.posted_at
E        +  and   datetime.date(2022, 2, 10) = <built-in method date of datetime.datetime object at 0x401ac32660>()
E        +    where <built-in method date of datetime.datetime object at 0x401ac32660> = datetime.datetime(2022, 2, 10, 15, 58, 50, 113551).date
E        +      where datetime.datetime(2022, 2, 10, 15, 58, 50, 113551) = <built-in method now of type object at 0x400ca35d60>()
E        +        where <built-in method now of type object at 0x400ca35d60> = <class 'datetime.datetime'>.now
E        +          where <class 'datetime.datetime'> = datetime.datetime

blog/tests/test_post.py:33: AssertionError
=============================== warnings summary ===============================
blog/tests/test_post.py::test_default_user_is_root
  /home/web/.local/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1409: RuntimeWarning: DateTimeField Post.posted_at received a naive datetime (2022-02-09 15:58:50.076302) while time zone support is active.
    warnings.warn("DateTimeField %s received a naive datetime (%s)"

blog/tests/test_post.py::test_default_edited_time_is_set
  /home/web/.local/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1409: RuntimeWarning: DateTimeField Post.posted_at received a naive datetime (2022-02-09 15:58:50.098384) while time zone support is active.
    warnings.warn("DateTimeField %s received a naive datetime (%s)"

blog/tests/test_post.py::test_default_posted_time_is_set
  /home/web/.local/lib/python3.9/site-packages/django/db/models/fields/__init__.py:1409: RuntimeWarning: DateTimeField Post.posted_at received a naive datetime (2022-02-09 15:58:50.111771) while time zone support is active.
    warnings.warn("DateTimeField %s received a naive datetime (%s)"

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED blog/tests/test_post.py::test_default_posted_time_is_set - AssertionEr...
=================== 1 failed, 2 passed, 3 warnings in 6.54s ====================